sudo: false
dist: trusty

language: go

go:
  - 1.4.3
  - 1.5.4
  - 1.6.3
  - 1.7.3

install:
  - # Do nothing.

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet -structtags=false .
